const ERROR_CODES = {
  INTERNAL_ERROR: 'Internal server error',
  AUTH_REQUIRED: 'Authentication required',
  INVALID_CREDENTIALS: 'Invalid username or password',
  INVALID_TOKEN: 'Invalid or expired token',
  USER_NOT_FOUND: 'User not found',
  ACCOUNT_INACTIVE: 'Account is inactive. Contact your administrator.',
  FORBIDDEN: 'Forbidden',
  USERNAME_EXISTS: 'Username already exists',
  CANNOT_DEACTIVATE_SELF: 'Cannot deactivate your own account',
  CANNOT_DELETE_SELF: 'Cannot delete your own account',
  VALIDATION_FAILED: 'Validation failed',
  VALIDATION_USERNAME_REQUIRED: 'Username is required',
  VALIDATION_PASSWORD_REQUIRED: 'Password is required',
  VALIDATION_NAME_REQUIRED: 'Name is required',
  VALIDATION_PASSWORD_MIN: 'Password must be at least 6 characters',
  VALIDATION_INVALID_ROLE: 'Invalid role',
  TOURIST_NOT_FOUND: 'Tourist not found',
  PACKAGE_NOT_FOUND: 'Package not found',
  PROPERTY_NOT_FOUND: 'Property not found',
  PROPERTY_INACTIVE: 'Property is inactive',
  DUPLICATE_ACCOMMODATION: 'Duplicate accommodation in package',
  PROPERTY_ID_REQUIRED: 'Property ID is required for accommodation items',
  PARK_NOT_FOUND: 'Park not found',
  ACTIVITY_NOT_FOUND: 'Activity not found',
  ACTIVITY_INACTIVE: 'Activity is inactive',
  DUPLICATE_ACTIVITY: 'Duplicate activity in package',
  ACTIVITY_ID_REQUIRED: 'Activity ID is required for activity items',
  HANDOFF_NOT_FOUND: 'Handoff not found',
  HANDOFF_NOT_PENDING: 'Handoff is not pending',
  PACKAGE_NOT_READY: 'Package is not ready for handoff',
  EXPENSE_NOT_FOUND: 'Expense not found',
  SALARY_ALREADY_PAID: 'Salary already paid for this period',
  SALARY_NOT_SET: 'Monthly salary is not set for this employee',
  NOT_AN_EMPLOYEE: 'Target user is not an employee',
  INVALID_PAY_PERIOD: 'Invalid pay period. Use YYYY-MM',
  PACKAGE_SPENDING_NOT_FOUND: 'Package spending not found',
  PACKAGE_LOG_NOT_FOUND: 'Package log not found',
};

module.exports = ERROR_CODES;
